### PR TITLE
Support Kaltura's HTML5 player (v2)

### PR DESCRIPTION
**Pull request by jessp01**
This pull adds support for Kaltura player embeds (using an `iframe` tag).

Thanks in advance for your consideration,

### CODE REVIEW

**Comment by jessp01** [comment]
Hi @cookpete,

First of all, a very useful project, well done:)
Would you please review this pull request? It basically follows the same implementation as `Streamable`, using the Embed.ly `playerjs` lib.

Thanks,

**Comment by cookpete** [comment]
Hi @jessp01, sorry for how long it has taken to get back to you on this.

I'm running it locally and not much is working. Pause doesn't work, seeking doesn't work, volume change only works when you set it to `0`, and none of the callback props are called (onPlay, onPause, etc).

The player API docs also don’t mention anything about supporting `player.js`: http://player.kaltura.com/docs/api

**Comment by jessp01** [comment]
Hi @cookpete,

Thanks for getting back to me. When you say you're running it locally, do you mean with the demo app (src/demo/App.js)? 
It worked okay when I tested but I will check again. Also could you please let me know which API ops you consider mandatory, or, in other words: must be implemented before the pull can be merged?

As for the documentation, indeed, it is lacking in that sense. The Kaltura player supports multiple embed methods and has its own API but when embedding in an `iframe` (which seems to be the preferred method for `react-player`, quite sensibly), using Embed.ly's `player.js` is the only way. 

Thanks again,

**Comment by jessp01** [comment]
Hi @cookpete ,

All basic APIs work now (tested using the demo app). If you feel it's important, I can implement the speed increase actions as well.

Let me know if this can be merged? 

Cheers,

**Comment by cookpete** [comment]
I think something must be broken with their player API? Things still aren't working for me.

Even the most basic interactive embed code (copied directly from their docs) doesn’t seem to work:

http://player.kaltura.com/modules/PlayersJsReceiver/tests/PlayersJsReceiver.qunit.html

```js
	var player = new playerjs.Player( document.getElementById('kaltura_player') );
	//listen to play start
	player.on(playerjs.Events.PLAY, function() {
	  // This is never called :(
		console.log('play');
	});
```

Live example: https://jsfiddle.net/zes7n2pw/

**Comment by cookpete** [comment]
There’s also this page that has a script tag that doesn't work:

https://developer.kaltura.com/player/web/getting-started-web

```html
  <script type="text/javascript" src="https://cdnapisec.kaltura.com/p/000000/embedPlaykitJs/uiconf_id/22222222"></script>

```

I get a 404 when I try the example as well as replace the conf_id and partner id with the ones from your sample URL:

image

**Comment by jessp01** [comment]
Hi @cookpete ,

Yes, I am aware of the fact that this demo (http://player.kaltura.com/modules/PlayersJsReceiver/tests/PlayersJsReceiver.qunit.html) does not work. I will try to get that fixed (not under my direct remit but I'll speak to the relevant people). 
But does the demo app not work for you following my last commit? It does for me.

Also, here's a standalone demo that works as well:
https://demo.kaltura.me/player.js.demo.html

The documentation you referenced (https://developer.kaltura.com/player/web/getting-started-web) pertains to Kaltura's player v7 (aka playKit). That's a completely different codebase I'm afraid (I agree it is confusing). I'll submit a pull to support that a bit later in the game, when it's a bit more mature.

**Comment by cookpete** [comment]
Added some tweaks and fixes, mainly around the `onReady` and event binding logic. Hopefully all good now. Thanks for the help @jessp01 👍

**Comment by jessp01** [comment]
Hi @cookpete,

Excellent. Thanks again for your time :)

**Comment by jessp01** [comment]
@cookpete - would it be possible for you to create a new release version?
Thanks,

**Comment by cookpete** [comment]
Would like to get some other stuff in first. Will publish soon 👍

**Comment by jessp01** [comment]
Cheers, @cookpete. Much appreciated.

**Pull request merged**
