### PR TITLE
Feature/add classname props

### PR DESCRIPTION
**Pull request by mixelburg**
Added proper className prop support

### CODE REVIEW

**Comment by cookpete** [comment]
Any additional props passed in to ReactPlayer are added as `{...attributes}` here. So I think `className` is already supported and this PR is redundant? Correct me if I’m wrong.

https://github.com/cookpete/react-player/blob/9775bb755af195e6f7e8bacfed436fcefb135354/src/ReactPlayer.js#L173

**Comment by mixelburg** [comment]
It is but the problem is that it isn't in the typescript docs

**Comment by mixelburg** [comment]
But yea, you are right, I think we should just add it to the typescript definition files

**Comment by cookpete** [comment]
Does the `[otherProps: string]: any` not cover it sufficiently? I guess it would be nice to be specific, but then you could say the same thing about any other possible "other" prop.

**Pull request closed without merging**
