### PR TITLE
PlaybackRate change feature

### PR DESCRIPTION
**Pull request by llopez95**
All is in the title. The last PR i made didn't pass Travis CI. Should be good now.

### CODE REVIEW

**Comment by llopez95** [comment]
Okay, I'm really not familiar with Travis CI.  Let me know if I need to do anything else.

Regards,

**Comment by CookPete** [comment]
You [don't need to generate `dist` files](https://github.com/CookPete/react-player/blob/master/CONTRIBUTING.md#dist-files) yourself. Remove from the commits (and squash) and I'm happy to merge.

**Comment by llopez95** [comment]
Okay, I did remove the dist files commit.
To be honest i'm not so used to Git then let me know if I should do anything else!

I'm happy to help and glad you have interest in this PR!

Regards,

**Comment by CookPete** [comment]
Fixed up and merged manually. Thanks!

**Pull request closed without merging**
