### PR TITLE
Use new Vimeo player.js API

### PR DESCRIPTION
**Pull request by nikolas**
These changes turn out to solve my big problem I'm having with issue #140.

Also addresses issue #90.

I'm sure there are things that are missing from here. I realize you have your own vimeo branch going - I'm putting this up here for reference, to share thoughts, etc., and because it solves my problem.

### CODE REVIEW

**Comment by nikolas** [comment]
Hmmm.. tests are passing for me locally (they're run in Firefox and Chromium). Looking into why travis is failing.

**Comment by CookPete** [comment]
Nice work @nikolas. My only issue is that I don't like the idea of directly `import`ing the vimeo package into the `ReactPlayer` library, which needlessly increases the package size even if the vimeo player is not used. This is why I load the vimeo SDK in using `load-script` in my branch (same with the youtube SDK). 

Is there anything different you have done compared to my attempt that I should keep in mind? What I'll probably end up doing is combining the wisdom of both before merging it in.

**Comment by nikolas** [comment]
Ah okay - good point with importing the vimeo package. I was wondering why you didn't do that with your branch and have the loadSDK stuff, but now I get it.

**Comment by CookPete** [comment]
Yeah I wanted to avoid a massive `ReactPlayer` bundle with every single SDK embedded into it, considering the majority of users will only use it for one or two types of URL (possibly just file paths, which uses no SDK at all).

**Pull request closed without merging**
