### PR TITLE
Remove Babel plugin add-module-exports to support TypeScript

### PR DESCRIPTION
**Pull request by jankarres**
See issue #193.

The plugin should works in JavaScript and TypeScript with this change.

### CODE REVIEW

**Comment by jankarres** [comment]
Anything further I have to do for merging? :)

**Comment by jankarres** [comment]
Anything further I have to do for merging, @CookPete? :)

**Comment by CookPete** [comment]
84d6c35ef444b1aef826f06a0728f288e151a35a should take care of this. Thanks for the PR but I didn't want to remove the plugin completely, just move it to the bower build. Committing `dist` files is also [unnecessary](https://github.com/CookPete/react-player/blob/master/CONTRIBUTING.md#dist-files).

**Comment by jankarres** [comment]
Works, thanks man!

**Pull request closed without merging**
