### PR TITLE
Add onSeek support for Youtube player

### PR DESCRIPTION
**Pull request by Adrian-stuff**
Hello.
Im making a "watch together" app and the "onSeek" event for youtube is not working.
I found this tutorial on google: https://simplernerd.com/js-youtube-seek/
i thought it would help other developer if they are using the player.

I just added a little code to the tutorial to detect seek when the player is paused.

    else if (data === PAUSED) {    
        const seekTimer = setInterval(() => {  
            if (                     
              this.prevTime !== this.getCurrentTime() &&   // Paused seek
              isSubArrayEnd(this._sequence, [PAUSED])
            ) {
              onSeek(this.getCurrentTime())
              // this._sequence = []
              this.prevTime = this.getCurrentTime()
            }
         }, 750)
    }
Implements the `onSeek` event for YouTube. Fixes https://github.com/cookpete/react-player/issues/1243

### CODE REVIEW

**Comment by JohnRock0422** [comment]
Hi, I got same issue.

Vimeo works, but Youtube is not.

**Comment by ccowen** [comment]
I cannot calculate elapsed time unless I trigger my seek bar, it does not work until then. So it doesn't work when the video plays unless I use my seek bar.

Is this because this function doesn't work? I'm a little confused because it works in the demo.

**Comment by ccowen** [comment]
> I cannot calculate elapsed time unless I trigger my seek bar, it does not work until then. So it doesn't work when the video plays unless I use my seek bar.
> 
> Is this because this onSeek function doesn't work? I'm a little confused because it works in the demo.

This behavior is not the same when it is deployed. I guess its a cross origin thing? I thought it was related to this function, but I guess not

**Comment by stellarhoof** [comment]
Any updates on this?

**Comment by bytefulness** [comment]
@cookpete We're still facing the issue is there any updates?

**Comment by Adrian-stuff** [comment]
> I cannot calculate elapsed time unless I trigger my seek bar, it does not work until then. So it doesn't work when the video plays unless I use my seek bar.
> 
> Is this because this onSeek function doesn't work? I'm a little confused because it works in the demo.

onSeek will only be triggered when you seek on the bar, if you want to get the elapsed time every second you can have a setInteval function that will trigger every second to calculate the elapsed time based on the currentTime on the player

**Comment by luwes** [comment]
thanks for the contribution, closing due to out of date.

**Pull request closed without merging**
