### PR TITLE
Updated hls.js documentation link in README.md

### PR DESCRIPTION
**Pull request by borozcod**
Updated hls.js documentation link.

### CODE REVIEW

**Comment by CookPete** [comment]
Seems like the only change here is removing the `#fine-tuning` anchor to load the correct section of the page. Why remove it?

**Comment by borozcod** [comment]
I believe they changed the /doc to /docs I can add the #fine-tuning at the end of the link and commit that change.

**Comment by CookPete** [comment]
Good spot @borozcod. Yeah if you add `#fine-tuning` back I'm happy to merge this up.

**Comment by borozcod** [comment]
Committed that change. Thank you.

**Comment by CookPete** [comment]
Thanks!

**Pull request merged**
