### PR TITLE
added hls error recovery

### PR DESCRIPTION
**Pull request by iambumblehead**
add attempt to recover from hls errors

### CODE REVIEW

**Comment by iambumblehead** [comment]
@CookPete it seems travic-ci is unable to complete the test sequence. Would you take a look at my PR?

**Comment by CookPete** [comment]
It seems like a `MEDIA_ERROR` is occuring pretty consistently when seeking towards the end of a HLS video. `recoverMediaError()` is causing a loop to occur as it attempts to play the media immediately and causes another `MEDIA_ERROR`, whereas the demo video seems to recover automatically without having to call `recoverMediaError()`.

I think we are better off passing `Hls.Events.ERROR` through to the `onError` callback, and possibly passing through the `hls` object. Then users can just implement any sort of recovery logic that they want.

**Comment by CookPete** [comment]
As of `1.3.0`, hls.js errors are now passed as `onError(e, data, hlsInstance, hlsGlobal)`

You could implement the same recovery logic like so:

```jsx
function onError (e, data, hlsInstance, hlsGlobal) {
  if (!hlsGlobal) {
    // Probably not a HLS error
    return
  }
  switch (data.type) {
    case hlsGlobal.ErrorTypes.NETWORK_ERROR:
      // try to recover network error
      // hls: fatal network error encountered, trying to recover
      hlsInstance.startLoad()
      break
    case hlsGlobal.ErrorTypes.MEDIA_ERROR:
      // hls: fatal media error encountered, trying to recover
      hlsInstance.recoverMediaError()
      break
    default:
      // cannot recover
      hlsInstance.destroy()
      break
  }
}

<ReactPlayer url={HLS_URL} onError={onError} />
```

Although beware of causing loops when seeking.

**Comment by iambumblehead** [comment]
@CookPete I copied your recommendation here. its a great starting point :), thanks

**Pull request closed without merging**
