### PR TITLE
Add Cloudflare Stream content player

### PR DESCRIPTION
**Pull request by yubodiwu**
Cloudflare Stream is an easy-to-use, affordable, on-demand video streaming platform.
It handles video storage, encoding, and a customizable player with Cloudflare’s fast, secure, and reliable global network

This adds support for their player using their Javascript API.

### CODE REVIEW

**Comment by nmklotas** [comment]
Nice! Would be cool to get ir merged :}

**Comment by nmklotas** [comment]
@CookPete can this be merged ?:)

**Comment by CookPete** [comment]
According to [this page](https://developers.cloudflare.com/stream/video-playback/third-party-players/), Cloudflare Streams are available at:

- `https://videodelivery.net/{id}/manifest/video.m3u8` (HLS)
- `https://videodelivery.net/{id}/manifest/video.mpd` (Dash)

ReactPlayer already has support for HLS and Dash streams, so you can just extract the ID from your Cloudflare Steam URL, and pass the `.m3u8` or `.mpd` address above in to ReactPlayer as the `url`.

It would be nice if ReactPlayer did this for you, so I'll leave this PR open as a reminder, but adding a whole new player for streams that are already indirectly supported seems unnecessary. Nice work regardless 👍

**Comment by CookPete** [comment]
Cloudflare Stream URLs are now supported in `2.4.0`. It just maps `https://watch.cloudflarestream.com/{id}` to `https://videodelivery.net/{id}/manifest/video.m3u8` and `hls.js` kicks in to play the stream.

**Comment by yubodiwu** [comment]
oh nice! Thanks @CookPete!

**Pull request closed without merging**
