### PR TITLE
apply interface onProgressProps at base.d.ts

### PR DESCRIPTION
**Pull request by hyesungoh**
Hello pete, I apply some interface at `base.d.ts`

- generate and apply `onProgressProps`

```ts
export interface onProgressProps {
    played: number;
    playedSeconds: number;
    loaded: number;
    loadedSeconds: number;
}

export interface BaseReactPlayerProps {
...
onProgress?: (state: onProgressProps) => void;
...
}
```

#### Expected User Behavior

- using props type for custom onProgress 

```tsx
import ReactPlayer, { onProgressProps } from "react-player";

const foo = () => {
  const onProgress = ({playedSeconds}: onProgressProps) => {
      // something
  }

  return <ReactPlayer url={url} onProgress={onProgress} />
};
```

### CODE REVIEW

**Comment by Yasamato** [comment]
Nice idea! I would only recommend [sticking to the existing code styling](https://github.com/CookPete/react-player/blob/master/CONTRIBUTING.md#linting) to prevent merge conflicts...

**Comment by hyesungoh** [comment]
@Yasamato I applied code styling! thank you for letting me know :D

**Comment by cookpete** [comment]
Updated to `OnProgressProps` (capitalized) to be consistent with other interfaces. Nice work!

**Comment by cookpete** [comment]
Published in `2.11.0`. Sorry for the delay.

**Pull request merged**
